# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
# write your code here
A = torch.Tensor([[1, 2], [3, 4]])
B = torch.Tensor([[10, 20], [30, 40]])

C = A + B
print(A)
print(B)
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [3]:
# write your code here
print(A.dim())
print(A.size())
print(A.type())

2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [4]:
# write your code here
A = A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [5]:
# write your code here
D = torch.rand(5, 2, 3)
print(D)
print(D.type())
print(D.dim())
print(D.size())
print(D.size(1))

tensor([[[0.4696, 0.4450, 0.6029],
         [0.6775, 0.3016, 0.0908]],

        [[0.4836, 0.1990, 0.7776],
         [0.2671, 0.1030, 0.9850]],

        [[0.3770, 0.0482, 0.3977],
         [0.6349, 0.5141, 0.3995]],

        [[0.9460, 0.9524, 0.6459],
         [0.2036, 0.9167, 0.7483]],

        [[0.1844, 0.3590, 0.9186],
         [0.5342, 0.6739, 0.7826]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [6]:
# write your code here
# write your code here
E = torch.zeros(2, 3, 4, 5)
print(E)
print(E.type())
print(E.dim())
print(E.size())

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
torch.FloatTensor
4
torch.Size([2, 3, 4, 5])
